/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConProfessor;
import BriamBank.Model.Professor;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel
 */
public class Admin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form Admin
     */
    public Admin() {
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        initComponents();
        adicionarHintText();
        listar();;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPesquiar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtRMProfessor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPesquiar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Rm do Professor");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Email do Professor");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Senha do Professor");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Nome do Professor");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPesquiarLayout = new javax.swing.GroupLayout(btnPesquiar);
        btnPesquiar.setLayout(btnPesquiarLayout);
        btnPesquiarLayout.setHorizontalGroup(
            btnPesquiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPesquiarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(btnPesquiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnPesquiarLayout.createSequentialGroup()
                        .addGroup(btnPesquiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRMProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(btnPesquiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir)
                            .addComponent(jButton1))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btnPesquiarLayout.setVerticalGroup(
            btnPesquiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPesquiarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnPesquiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRMProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnPesquiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addGap(21, 21, 21))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(btnVoltar)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String rmStr = txtRMProfessor.getText().trim();

            int rm;
            try {
                rm = Integer.parseInt(rmStr);
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(rootPane, "O campo RM deve ser um numero valido!");
                return;
            }

            if (rmStr.length() != 5) {
                JOptionPane.showMessageDialog(rootPane, "RM inválido! Deve ter exatamente 5 dígitos.");
                return;
            }

            ConProfessor conProfessor = new ConProfessor();

            Professor professor = conProfessor.pesquisarPorRM(rm);

            if (professor.getNome_Professor() != null) {
                txtNome.setText(professor.getNome_Professor());
                txtEmail.setText(professor.getEMAIL_Professor());
                txtSenha.setText(professor.getSENHA_Professor());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Professor não encontrado");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
            txtRMProfessor.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {

            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente editar?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                /*Pegando os valores dos Text Fields*/
                String rmStr = txtRMProfessor.getText().trim();
                String nome = txtNome.getText().trim();
                String email = txtEmail.getText().trim();
                String senha = txtSenha.getText().trim();

                /*Validação deve ser posta nessa área*/
                if (rmStr.isEmpty() || nome.isEmpty() || email.isEmpty() || senha.isEmpty()
                        || rmStr.equals("RM do Professor") || nome.equals("Nome do Professor")
                        || email.equals("Email do Professor") || senha.equals("Senha do Professor")) {
                    JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos!");
                    return;
                } else if (!rmStr.matches("\\d+")) {
                    JOptionPane.showMessageDialog(rootPane, "O RM deve conter apenas números!");
                    return;
                } else if (rmStr.length() != 5) {
                    JOptionPane.showMessageDialog(rootPane, "RM inválido! Deve ter exatamente 5 dígitos.");
                    return;
                } else if (nome.length() > 30) {
                    JOptionPane.showMessageDialog(rootPane, "O nome deve ter no máximo 30 caracteres");
                    return;
                } else if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
                    JOptionPane.showMessageDialog(rootPane, "Email inválido!");
                    return;
                } else if (email.length() > 30) {
                    JOptionPane.showMessageDialog(rootPane, "O Email deve ter no maximo 30 caracteres");
                    return;
                } else if (!senha.matches("[0-9a-zA-Z$*&@#]{8,32}")) {
                    JOptionPane.showMessageDialog(rootPane, "A senha deve ter entre 8 e 32 caracteres e ao menos 1 caracter especial ($*&@#)!");
                    return;
                }

                int rm;
                try {
                    rm = Integer.parseInt(rmStr);
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(rootPane, "O campo RM deve ser um numero valido!");
                    return;
                }

                Professor professor = new Professor();
                professor.setRM_Professor(rm);
                professor.setNome_Professor(nome);
                professor.setEMAIL_Professor(email);
                professor.setSENHA_Professor(senha);

                ConProfessor conProfessor = new ConProfessor();
                boolean confirm = conProfessor.editar(professor);
                if (confirm) {
                    JOptionPane.showMessageDialog(rootPane, "Edição feita com Sucesso!!");
                    listar();
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            String rmStr = txtRMProfessor.getText().trim();

            if (rmStr.isEmpty() || rmStr.equals("RM do Professor")) {
                JOptionPane.showMessageDialog(rootPane, "Por favor, digite o RM do professor!");
                return;
            }

            int rm;
            try {
                rm = Integer.parseInt(rmStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "O RM deve ser um número válido!");
                return;
            }

            if (rmStr.length() != 5) {
                JOptionPane.showMessageDialog(rootPane, "RM inválido! Deve ter exatamente 5 dígitos.");
                return;
            }

            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir ?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                ConProfessor conProfessor = new ConProfessor();

                /*Pega o rm do professor pesquisado, e usa para excluir*/
                conProfessor.excluir(rm);

                /*Mensagem de sucesso*/
                JOptionPane.showMessageDialog(rootPane, "Registro atualizado com sucesso!!!");
                listar();
            }
        } catch (Exception ex) {
            /*Mensagem de erro*/
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro:" + ex);
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            Login novaTela = new Login();
            novaTela.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro e o programa sera finalizado");
            System.exit(0);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JPanel btnPesquiar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRMProfessor;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables

    public void listar() {
        Vector cabecalho = new Vector();
        try {
            cabecalho.addElement("RM");
            cabecalho.addElement("Nome");
            cabecalho.addElement("Email");

            ConProfessor conProfessor = new ConProfessor();
            if (conProfessor.listar() == null) {
                JOptionPane.showMessageDialog(rootPane, "Ocorreu uma falha durante a exibição dos dados, tente novamente mais tarde");
            }

            jTable1.setModel(new DefaultTableModel(conProfessor.listar(), cabecalho));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu uma falha durante a exibição dos dados, tente novamente mais tarde");

        }
    }

    private void adicionarHintText() {

        txtRMProfessor.setText("RM do Professor");
        txtRMProfessor.setForeground(Color.GRAY);

        txtRMProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtRMProfessor.getText().equals("RM do Professor")) {
                    txtRMProfessor.setText("");
                    txtRMProfessor.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtRMProfessor.getText().isEmpty()) {
                    txtRMProfessor.setText("RM do Professor");
                    txtRMProfessor.setForeground(Color.GRAY);
                }
            }
        });

        txtNome.setText("Nome do Professor");
        txtNome.setForeground(Color.GRAY);

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtNome.getText().equals("Nome do Professor")) {
                    txtNome.setText("");
                    txtNome.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtNome.getText().isEmpty()) {
                    txtNome.setText("Nome do Professor");
                    txtNome.setForeground(Color.GRAY);
                }
            }
        });

        txtEmail.setText("Email do Professor");
        txtEmail.setForeground(Color.GRAY);

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtEmail.getText().equals("Email do Professor")) {
                    txtEmail.setText("");
                    txtEmail.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtEmail.getText().isEmpty()) {
                    txtEmail.setText("Email do Professor");
                    txtEmail.setForeground(Color.GRAY);
                }
            }
        });

        txtSenha.setText("Senha d Professor");
        txtSenha.setForeground(Color.GRAY);

        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtSenha.getText().equals("Senha d Professor")) {
                    txtSenha.setText("");
                    txtSenha.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtSenha.getText().isEmpty()) {
                    txtSenha.setText("Senha d Professor");
                    txtSenha.setForeground(Color.GRAY);
                }
            }
        });
    }
}
