/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConAluno;
import BriamBank.Controller.ConTurma;
import BriamBank.Model.Session;
import BriamBank.Model.Turma;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kauax
 */

public class AlunoList extends javax.swing.JFrame {

    /*Guarda o id da turma*/
    private int CodTurma;
    
    /*Guarda registros de erros*/
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlunoList.class.getName());

    /**
     * Creates new form AlunoList
     */
    public AlunoList() {
        
        /*Verifica se há um professor logaddo, se não há ele dá a mensagem*/
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane, "Não é possivel acessar essa tela sem realizar o login, o programa será encerrado por segurança");
            System.exit(0);
        }
        
        /*Define o icone da janela*/
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());
        
        /*Carrega oss componentes das telas*/
        initComponents();
        
        /*Mensagem em caso de falha*/
        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao tentar acessar a tela, tente novamente mais tarde");
    }

    public AlunoList(int CodTurma) {
        
        /*Verifica se há um professor logaddo, se não há ele dá a mensagem*/
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane, "Não é possivel acessar essa tela sem realizar o login");
            System.exit(0);
        }
        
        /*Define o icone da janela*/
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        
        /*Armazena o codigo da turma*/
        this.CodTurma = CodTurma;
        
        /*Carrega oss componentes das telas*/
        initComponents();
        
        /*Instanciando e criando o objeto*/
        ConTurma conTurma = new ConTurma();
        
        /*Busca dados das turmas*/
        Turma turma = conTurma.retornaTurma(CodTurma);
        
        /*Pega os alunos e adiciona eles na lista de alunos*/
        jLabel9.setText("Alunos do " + turma.getCURSO_Turma() + "-" + turma.getGRUPO_Turma());
        listar(CodTurma);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        menuLateral1 = new BriamBank.Model.componentes.MenuLateral();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnVoltar = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Alunos do Grupo A");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Id", "Rm", "Pontos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jToggleButton1.setText("Atualizar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 122, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Excluir Turma");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addGap(667, 667, 667))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(jButton1))
                        .addGap(37, 37, 37))))
            .addComponent(menuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            
            /*atualiza a tabela com a lista de alunos*/
            listar(CodTurma);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro, ERRO: " + ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            ConTurma conTurma = new ConTurma();
            /*Busca dados dda turma atual*/
            Turma turma = conTurma.pesquisarID(String.valueOf(this.CodTurma));
            
            //Abre a tela de GrupoMenu
            GrupoMenu grupoMenu = new GrupoMenu(turma.getNOME_Turma());
            grupoMenu.setLocationRelativeTo(null);
            grupoMenu.setVisible(true);
            
            /*Fecha a tela atual*/
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o grupo", "Confirmar", JOptionPane.YES_NO_OPTION);
            
            if (op == JOptionPane.YES_OPTION) {
                ConTurma conTurma = new ConTurma();

                /*Exclui o grupo no banco de dados*/
                conTurma.excluir(CodTurma);

                /*abre a tela principal de turmas*/
                MenuTurma novaTela = new MenuTurma();
                novaTela.setVisible(true);

                /*Fecha a tela atual*/
                this.dispose();
            }
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MenuTurma.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlunoList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private BriamBank.Model.componentes.MenuLateral menuLateral1;
    // End of variables declaration//GEN-END:variables
    public void listar(Integer CodTurma) {
        Vector cabecalho = new Vector();
        try {
            
            /*Cria o cabeçalho da tabela*/
            cabecalho.addElement("Id");
            cabecalho.addElement("Nome");
            cabecalho.addElement("Rm");
            cabecalho.addElement("Pontos");
        
            /*Instanciando e criando o objeto ConAluno*/
            ConAluno conAluno = new ConAluno();
            if (conAluno.listarPorTurma(CodTurma) == null) {
                JOptionPane.showMessageDialog(rootPane, "Ocorreu uma falha durante a exibição dos dados, tente novamente mais tarde");
            }
            
            /*Chama listarPorTurma(CodTurma) para buscar os dados do banco
            Coloca os dados dentro da tabela*/
            jTable1.setModel(new DefaultTableModel(conAluno.listarPorTurma(CodTurma), cabecalho));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu uma falha durante a exibição dos dados, tente novamente mais tarde");

        }
    }

}
