/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConProfessor;
import BriamBank.Model.Professor;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class CadastroProfessor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroProfessor.class.getName());

    /**
     * Creates new form CadastroProfessor
     */
    public CadastroProfessor() {
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());
        initComponents();
        adicionarHintText();

        java.awt.EventQueue.invokeLater(() -> {
            jLabel1.requestFocusInWindow();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        txtEMAIL = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        txtRM = new javax.swing.JTextField();
        txtNOME = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtSenhaConfirm = new javax.swing.JPasswordField();
        btnSenha2 = new javax.swing.JToggleButton();
        btnSenha1 = new javax.swing.JToggleButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("BrianBank");

        txtEMAIL.setToolTipText("");
        txtEMAIL.setPreferredSize(new java.awt.Dimension(128, 44));
        txtEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEMAILActionPerformed(evt);
            }
        });

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 122, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cadastrar");
        jButton2.setPreferredSize(new java.awt.Dimension(128, 44));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtRM.setToolTipText("");
        txtRM.setPreferredSize(new java.awt.Dimension(128, 44));
        txtRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRMActionPerformed(evt);
            }
        });

        txtNOME.setToolTipText("");
        txtNOME.setPreferredSize(new java.awt.Dimension(128, 44));

        jButton3.setBackground(new java.awt.Color(0, 122, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancelar");
        jButton3.setPreferredSize(new java.awt.Dimension(128, 44));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtSenhaConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaConfirmActionPerformed(evt);
            }
        });

        btnSenha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/view.png"))); // NOI18N
        btnSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenha2ActionPerformed(evt);
            }
        });

        btnSenha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/view.png"))); // NOI18N
        btnSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenha1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSenha)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSenhaConfirm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59)
                .addComponent(txtRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtNOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtEMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSenha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSenha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSenhaConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
           
        // Pegando e limpando espaços dos valores digitados
        String rmText = txtRM.getText().trim();
        String nome = txtNOME.getText().trim();
        String email = txtEMAIL.getText().trim();
        String senha = new String(txtSenha.getPassword()).trim();
        String senhac = new String(txtSenhaConfirm.getPassword()).trim();

        // Verifica se algum campo está vazio ou ainda com o texto placeholder
        if (rmText.isEmpty() || rmText.equals("Digite seu RM")
                || nome.isEmpty() || nome.equals("Digite seu Nome")
                || email.isEmpty() || email.equals("Digite seu E-Mail")
                || senha.isEmpty() || senha.equals("Digite sua senha")
                || senhac.isEmpty() || senha.equals("Confirme sua senha")) {

            JOptionPane.showMessageDialog(rootPane, "Todos os campos devem estar preenchidos");

        // RM só pode ter números
        } else if (!rmText.matches("\\d+")) {
            JOptionPane.showMessageDialog(rootPane, "O RM deve conter apenas números!");

        // RM deve ter exatamente 5 dígitos
        } else if (rmText.length() != 5) {
            JOptionPane.showMessageDialog(rootPane, "RM inválido! Deve ter exatamente 5 dígitos.");

        // Nome não pode passar de 30 caracteres
        } else if (nome.length() > 30) {
            JOptionPane.showMessageDialog(rootPane, "O nome deve ter no máximo 30 caracteres");

        // Verifica formato do email
        } else if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(rootPane, "Email inválido!");

        // Email também não pode passar de 30 caracteres
        } else if (email.length() > 30) {
            JOptionPane.showMessageDialog(rootPane, "O Email deve ter no maximo 30 caracteres");

        // Senha precisa ter 8 a 32 caracteres e ao menos 1 char especial
        } else if (!senha.matches("[0-9a-zA-Z$*&@#]{8,32}")) {
            JOptionPane.showMessageDialog(rootPane, "A senha deve ter entre 8 e 32 caracteres e ao menos 1 caracter especial ($*&@#)!");

        // Confirmação de senha deve ser igual
        } else if (!senhac.equals(senha)) {
            JOptionPane.showMessageDialog(rootPane, "As senhas não são iguais!");
        } else {
            // Se tudo estiver OK, converte RM para inteiro
            int rm = Integer.parseInt(rmText);

            // Cria o objeto professor com os dados informados
            Professor prof = new Professor();
            prof.setRM_Professor(rm);
            prof.setNome_Professor(nome);
            prof.setEMAIL_Professor(email);
            prof.setSENHA_Professor(senha);

            // Usa o controller para tentar cadastrar no banco
            ConProfessor con = new ConProfessor();
            boolean sucesso = con.cadastrar(prof);

            // Se retornou true, significa que cadastrou
            if (sucesso) {
                JOptionPane.showMessageDialog(rootPane, "Professor cadastrado com sucesso!");

                // Abre a tela de login e fecha a tela atual
                Login novaTela = new Login();
                novaTela.setVisible(true);
                this.dispose();
            }
        }

    } catch (Exception ex) {
        // Caso aconteça algum erro inesperado
        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado: " + ex.getMessage());
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRMActionPerformed

    private void txtEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEMAILActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        Login novaTela = new Login();
        novaTela.setVisible(true);
        this.dispose(); // Fecha a tela atual
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSenhaConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaConfirmActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenha1ActionPerformed
        try {
        // Se estiver mascarado, remove a máscara
        if (txtSenha.getEchoChar() == '•') {
            txtSenha.setEchoChar((char) 0);
            btnSenha1.setIcon(new ImageIcon(getClass().getResource("/assets/icons/hide.png")));
        } else {
            // Se estiver visível, coloca a máscara de volta
            txtSenha.setEchoChar('•');
            btnSenha1.setIcon(new ImageIcon(getClass().getResource("/assets/icons/view.png")));
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
    }

    }//GEN-LAST:event_btnSenha1ActionPerformed

    private void btnSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenha2ActionPerformed
        try {
            if (txtSenhaConfirm.getEchoChar() == '•') {
                txtSenhaConfirm.setEchoChar((char) 0);
                btnSenha2.setIcon(new ImageIcon(getClass().getResource("/assets/icons/hide.png")));
            } else {
                txtSenhaConfirm.setEchoChar('•');
                btnSenha2.setIcon(new ImageIcon(getClass().getResource("/assets/icons/view.png")));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_btnSenha2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroProfessor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSenha1;
    private javax.swing.JToggleButton btnSenha2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtRM;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaConfirm;
    // End of variables declaration//GEN-END:variables
    private void adicionarHintText() {

        // HINT do EMAIL
        txtEMAIL.setText("Digite seu E-Mail");
        txtEMAIL.setForeground(Color.GRAY);

        txtEMAIL.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                // Remove o hint quando o usuário clica
                if (txtEMAIL.getText().equals("Digite seu E-Mail")) {
                    txtEMAIL.setText("");
                    txtEMAIL.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                // Coloca o hint de volta se o campo foi deixado vazio
                if (txtEMAIL.getText().isEmpty()) {
                    txtEMAIL.setText("Digite seu E-Mail");
                    txtEMAIL.setForeground(Color.GRAY);
                }
            }
        });

        // HINT da SENHA
        txtSenha.setText("Digite sua senha");
        txtSenha.setForeground(Color.GRAY);

        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtSenha.getText().equals("Digite sua senha")) {
                    txtSenha.setText("");
                    txtSenha.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtSenha.getText().isEmpty()) {
                    txtSenha.setText("Digite sua senha");
                    txtSenha.setForeground(Color.GRAY);
                }
            }
        });

        // HINT do RM
        txtRM.setText("Digite seu RM");
        txtRM.setForeground(Color.GRAY);

        txtRM.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtRM.getText().equals("Digite seu RM")) {
                    txtRM.setText("");
                    txtRM.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtRM.getText().isEmpty()) {
                    txtRM.setText("Digite seu RM");
                    txtRM.setForeground(Color.GRAY);
                }
            }
        });

        // HINT da CONFIRMAÇÃO DE SENHA
        txtSenhaConfirm.setText("Confirme sua senha");
        txtSenhaConfirm.setForeground(Color.GRAY);

        txtSenhaConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtSenhaConfirm.getText().equals("Confirme sua senha")) {
                    txtSenhaConfirm.setText("");
                    txtSenhaConfirm.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtSenhaConfirm.getText().isEmpty()) {
                    txtSenhaConfirm.setText("Confirme sua senha");
                    txtSenhaConfirm.setForeground(Color.GRAY);
                }
            }
        });

        // HINT do NOME
        txtNOME.setText("Digite seu Nome");
        txtNOME.setForeground(Color.GRAY);

        txtNOME.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtNOME.getText().equals("Digite seu Nome")) {
                    txtNOME.setText("");
                    txtNOME.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtNOME.getText().isEmpty()) {
                    txtNOME.setText("Digite seu Nome");
                    txtNOME.setForeground(Color.GRAY);
                }
            }
        });
    }


}
