/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConAluno;
import BriamBank.Controller.ConProfessor;
import BriamBank.Controller.ConTurma;
import BriamBank.Model.Aluno;
import BriamBank.Model.Session;
import BriamBank.Model.Turma;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LABINFO
 */
public class CadAluno extends javax.swing.JFrame {

    /**
     * Creates new form CadAluno
     */
    public CadAluno() {
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane, "Não é possivel acessar essa tela sem realizar o login, o programa será encerrado por segurança");
            System.exit(0);
        }
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        initComponents();
        carregarTurmas();
        adicionarHintText();

        java.awt.EventQueue.invokeLater(() -> {
            jLabel1.requestFocusInWindow();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRmAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmailAluno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdAluno = new javax.swing.JTextField();
        pesquisarA = new javax.swing.JButton();
        cadastrarA = new javax.swing.JButton();
        excluirA = new javax.swing.JButton();
        editarA = new javax.swing.JButton();
        comboTurma = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        menuLateral1 = new BriamBank.Model.componentes.MenuLateral();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 97, 97)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome Aluno");

        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Rm Aluno");

        txtRmAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRmAlunoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Turma");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        txtEmailAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAlunoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data de Nascimento");

        txtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Id do Aluno");

        pesquisarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pesquisarA.setText("Pesquisar");
        pesquisarA.setActionCommand("");
        pesquisarA.setBorder(null);
        pesquisarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAActionPerformed(evt);
            }
        });

        cadastrarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarA.setText("Cadastrar");
        cadastrarA.setBorder(null);
        cadastrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAActionPerformed(evt);
            }
        });

        excluirA.setBackground(new java.awt.Color(0, 122, 255));
        excluirA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        excluirA.setForeground(new java.awt.Color(255, 255, 255));
        excluirA.setText("Excluir");
        excluirA.setBorder(null);
        excluirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAActionPerformed(evt);
            }
        });

        editarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editarA.setText("Editar");
        editarA.setBorder(null);
        editarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAActionPerformed(evt);
            }
        });

        comboTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtRmAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(pesquisarA, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cadastrarA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(excluirA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editarA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRmAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadastrarA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(excluirA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editarA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciar Alunos");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRmAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRmAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRmAlunoActionPerformed

    private void txtEmailAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAlunoActionPerformed

    private void cadastrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAActionPerformed
        try {
            String nome = txtNomeAluno.getText().trim();
            String email = txtEmailAluno.getText().trim();
            String dataNasc = txtDataNasc.getText().trim();
            String turmaStr = (String) comboTurma.getSelectedItem();
            String rmStr = txtRmAluno.getText().trim();

            if (nome.isEmpty() || turmaStr.isEmpty() || rmStr.isEmpty() || nome.equals("Nome do aluno") || rmStr.equals("Rm do Aluno")) {
                JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos!");
                if (dataNasc.equals("AAAA-MM-DD")) {
                    dataNasc = null;
                }
                return;

            } else if (rmStr.length() > 5 || rmStr.length() < 5) {
                JOptionPane.showMessageDialog(rootPane, "o rm deve ter 5 digitos");
            }
            if (!email.isEmpty() && !email.equals("E-Mail do Aluno") && !email.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
                JOptionPane.showMessageDialog(rootPane, "Email inválido!");
                return;
            }

            int rm;
            try {
                rm = Integer.parseInt(rmStr);

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "O campo RM deve ser um número válido!");
                return;
            }

            if (dataNasc != null && !dataNasc.isEmpty() && !dataNasc.equals("AAAA-MM-DD")) {

                // valida formato AAAA-MM-DD
                if (!dataNasc.matches("\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])")) {
                    JOptionPane.showMessageDialog(rootPane, "Data de nascimento inválida! Use o formato AAAA-MM-DD.");
                    return;
                }

                int ano = Integer.parseInt(dataNasc.substring(0, 4));
                int anoAtual = LocalDate.now().getYear();

                if (ano < (anoAtual - 100) || ano > (anoAtual - 10)) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Ano inválido! Deve estar entre " + (anoAtual - 100) + " e " + (anoAtual - 10));
                    return;
                }
            } else {
                dataNasc = null;
            }

            ConTurma conTurma = new ConTurma();
            Turma turma = new Turma();

            Aluno aluno = new Aluno();
            ConAluno conAluno = new ConAluno();

            turma = conTurma.retornaTurma(turmaStr);

            aluno.setEMAIL_Aluno(email);
            aluno.setDATA_NASC_Aluno(dataNasc);
            aluno.setNOME_Aluno(nome);
            aluno.setCOD_Turma(turma.getID_Turma());
            aluno.setRM_Aluno(rm);

            boolean confirm = conAluno.cadastrar(aluno);

            if (confirm) {
                JOptionPane.showMessageDialog(rootPane, "Registro Cadastrado com Sucesso!!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_cadastrarAActionPerformed

    private void excluirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAActionPerformed
        try {

            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir ?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                ConAluno conAluno = new ConAluno();

                int id = Integer.parseInt(txtIdAluno.getText());
                conAluno.excluir(id);

                JOptionPane.showMessageDialog(rootPane, "Registro atualizado com sucesso!!!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro:" + ex);
        }
    }//GEN-LAST:event_excluirAActionPerformed

    private void editarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAActionPerformed
        try {

            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente editar ?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                String nome = txtNomeAluno.getText().trim();
                String email = txtEmailAluno.getText().trim();
                String dataNasc = txtDataNasc.getText().trim();
                String turmaStr = (String) comboTurma.getSelectedItem();
                String rmStr = txtRmAluno.getText().trim();
                String idStr = txtIdAluno.getText().trim();

                if (nome.isEmpty() || turmaStr.isEmpty() || rmStr.isEmpty() || nome.equals("Nome do aluno") || rmStr.equals("Rm do Aluno") || idStr.equals("ID") || idStr.isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos!");
                    if (dataNasc.equals("AAAA-MM-DD")) {
                        dataNasc = null;
                    }
                    return;

                } else if (rmStr.length() > 5 || rmStr.length() < 5) {
                    JOptionPane.showMessageDialog(rootPane, "o rm deve ter 5 digitos");
                }
                if (!email.isEmpty() && !email.equals("E-Mail do Aluno") && !email.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
                    JOptionPane.showMessageDialog(rootPane, "Email inválido!");
                    return;
                }

                int rm, id;
                try {
                    rm = Integer.parseInt(rmStr);
                    id = Integer.parseInt(idStr);
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(rootPane, "Campos RM, Turma e ID devem ser números válidos!");
                    return;
                }

                if (dataNasc != null && !dataNasc.isEmpty() && !dataNasc.equals("AAAA-MM-DD")) {

                    // valida formato AAAA-MM-DD
                    if (!dataNasc.matches("\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])")) {
                        JOptionPane.showMessageDialog(rootPane, "Data de nascimento inválida! Use o formato AAAA-MM-DD.");
                        return;
                    }

                    int ano = Integer.parseInt(dataNasc.substring(0, 4));
                    int anoAtual = LocalDate.now().getYear();

                    if (ano < (anoAtual - 100) || ano > (anoAtual - 10)) {
                        JOptionPane.showMessageDialog(rootPane,
                                "Ano inválido! Deve estar entre " + (anoAtual - 100) + " e " + (anoAtual - 10));
                        return;
                    }
                } else {
                    dataNasc = null;
                }

                ConTurma conTurma = new ConTurma();
                Turma turma = new Turma();

                Aluno aluno = new Aluno();
                ConAluno conAluno = new ConAluno();

                turma = conTurma.retornaTurma(turmaStr);

                aluno.setEMAIL_Aluno(email);
                aluno.setDATA_NASC_Aluno(dataNasc);
                aluno.setNOME_Aluno(nome);
                aluno.setCOD_Turma(turma.getID_Turma());
                aluno.setRM_Aluno(rm);
                aluno.setID_Aluno(id);

                boolean confirm = conAluno.editar(aluno);

                if (confirm) {
                    JOptionPane.showMessageDialog(rootPane, "Registro Atualizado com Sucesso!!");
                } else {
                    txtIdAluno.setText("");
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_editarAActionPerformed

    private void pesquisarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAActionPerformed
        try {
            Aluno aluno = new Aluno();
            ConAluno conAluno = new ConAluno();

            aluno.setID_Aluno(Integer.parseInt(txtIdAluno.getText()));
            aluno = conAluno.pesquisarID(String.valueOf(aluno.getID_Aluno()));
            if (aluno.getNOME_Aluno() != null) {
                ConTurma conTurma = new ConTurma();
                Turma turma = new Turma();

                turma = conTurma.retornaTurma(aluno.getCOD_Turma());

                txtIdAluno.setText(String.valueOf(aluno.getID_Aluno()));
                txtEmailAluno.setText(aluno.getEMAIL_Aluno());
                txtDataNasc.setText(aluno.getDATA_NASC_Aluno());

                comboTurma.setSelectedItem(turma.getNOME_Turma() + "-" + turma.getGRUPO_Turma());
                txtNomeAluno.setText(aluno.getNOME_Aluno());

                txtRmAluno.setText(String.valueOf(aluno.getRM_Aluno()));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Aluno não encontrado");
                txtIdAluno.setText("");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_pesquisarAActionPerformed

    private void comboTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTurmaActionPerformed

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void txtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            MenuCad novaTela = new MenuCad();
            novaTela.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAluno().setVisible(true);
            }
        });
    }

    public void carregarTurmas() {
        try {
            ConTurma conTurma = new ConTurma();

            Vector<Turma> turmas = conTurma.retornar_turmas();

            for (int i = 0; i < turmas.size(); i++) {
                Turma linha = turmas.get(i);

                comboTurma.addItem(linha.getNOME_Turma() + "-" + linha.getGRUPO_Turma());

                System.out.println("Turma: " + linha.getNOME_Turma() + " | Grupo: " + linha.getGRUPO_Turma() + " | ID: " + linha.getID_Turma());

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar dados do professor, tente novamente mais tarde");
            privarCampos();
        }
    }

    public void privarCampos() {
        txtIdAluno.setEnabled(false);
        txtEmailAluno.setEnabled(false);
        txtDataNasc.setEnabled(false);
        txtNomeAluno.setEnabled(false);
        excluirA.setEnabled(false);
        editarA.setEnabled(false);
        pesquisarA.setEnabled(false);
        cadastrarA.setEnabled(false);
        txtRmAluno.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarA;
    private javax.swing.JComboBox<String> comboTurma;
    private javax.swing.JButton editarA;
    private javax.swing.JButton excluirA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private BriamBank.Model.componentes.MenuLateral menuLateral1;
    private javax.swing.JButton pesquisarA;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEmailAluno;
    private javax.swing.JTextField txtIdAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtRmAluno;
    // End of variables declaration//GEN-END:variables
    private void adicionarHintText() {

        /*txtIdAluno.setEnabled(false);
        txtEmailAluno.setEnabled(false);
        txtDataNasc.setEnabled(false);
        txtNomeAluno.setEnabled(false);
        excluirA.setEnabled(false);
        editarA.setEnabled(false);
        pesquisarA.setEnabled(false);
        cadastrarA.setEnabled(false);
        txtRmAluno.setEnabled(false);*/
        // === HINT do campo EMAIL ===
        txtEmailAluno.setText("E-Mail do Aluno");
        txtEmailAluno.setForeground(Color.GRAY);

        txtEmailAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtEmailAluno.getText().equals("E-Mail do Aluno")) {
                    txtEmailAluno.setText("");
                    txtEmailAluno.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtEmailAluno.getText().isEmpty()) {
                    txtEmailAluno.setText("E-Mail do Aluno");
                    txtEmailAluno.setForeground(Color.GRAY);
                }
            }
        });

        // === HINT do campo Nome ===
        txtNomeAluno.setText("Nome do aluno");
        txtNomeAluno.setForeground(Color.GRAY);

        txtNomeAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtNomeAluno.getText().equals("Nome do aluno")) {
                    txtNomeAluno.setText("");
                    txtNomeAluno.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtNomeAluno.getText().isEmpty()) {
                    txtNomeAluno.setText("Nome do aluno");
                    txtNomeAluno.setForeground(Color.GRAY);
                }
            }
        });

        // === HINT do campo NASC ===
        txtDataNasc.setText("AAAA-MM-DD");
        txtDataNasc.setForeground(Color.GRAY);

        txtDataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtDataNasc.getText().equals("AAAA-MM-DD")) {
                    txtDataNasc.setText("");
                    txtDataNasc.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtDataNasc.getText().isEmpty()) {
                    txtDataNasc.setText("AAAA-MM-DD");
                    txtDataNasc.setForeground(Color.GRAY);
                }
            }
        });

        // === HINT do campo ID ===
        txtIdAluno.setText("ID");
        txtIdAluno.setForeground(Color.GRAY);

        txtIdAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtIdAluno.getText().equals("ID")) {
                    txtIdAluno.setText("");
                    txtIdAluno.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtIdAluno.getText().isEmpty()) {
                    txtIdAluno.setText("ID");
                    txtIdAluno.setForeground(Color.GRAY);
                }
            }
        });

        // === HINT do campo RM ===
        txtRmAluno.setText("Rm do Aluno");
        txtRmAluno.setForeground(Color.GRAY);

        txtRmAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtRmAluno.getText().equals("Rm do Aluno")) {
                    txtRmAluno.setText("");
                    txtRmAluno.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtRmAluno.getText().isEmpty()) {
                    txtRmAluno.setText("Rm do Aluno");
                    txtRmAluno.setForeground(Color.GRAY);
                }
            }
        });

    }
}
