package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConProfessor;
import BriamBank.Controller.ConTurma;
import BriamBank.Model.Professor;
import BriamBank.Model.Session;
import BriamBank.Model.Turma;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class CadTurma extends javax.swing.JFrame {

    /**
     * Creates new form CadTurma
     */
    public CadTurma() {
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane, "Não é possivel acessar essa tela sem realizar o login, o programa será encerrado por segurança");
            System.exit(0);
        }
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        initComponents();
        adicionarHintText();

        java.awt.EventQueue.invokeLater(() -> {
            jLabel1.requestFocusInWindow();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeTurma = new javax.swing.JTextField();
        cadastrarT = new javax.swing.JButton();
        excluirT = new javax.swing.JButton();
        editarT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIdTurma = new javax.swing.JTextField();
        pesquisarT = new javax.swing.JButton();
        txtGrupo = new javax.swing.JComboBox<>();
        txtPeriodo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        menuLateral1 = new BriamBank.Model.componentes.MenuLateral();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 97, 97)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ano");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Grupo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Curso");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Período");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nome da Turma");

        cadastrarT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarT.setText("Cadastrar");
        cadastrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarTActionPerformed(evt);
            }
        });

        excluirT.setBackground(new java.awt.Color(0, 122, 255));
        excluirT.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        excluirT.setForeground(new java.awt.Color(255, 255, 255));
        excluirT.setText("Excluir");
        excluirT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirTActionPerformed(evt);
            }
        });

        editarT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editarT.setText("Editar");
        editarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Id da Turma");

        txtIdTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTurmaActionPerformed(evt);
            }
        });

        pesquisarT.setText("Pesquisar");
        pesquisarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarTActionPerformed(evt);
            }
        });

        txtGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "Inteiro" }));

        txtPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhâ", "Tarde", "Noite", "Integral" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtGrupo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cadastrarT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(excluirT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editarT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIdTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(pesquisarT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(excluirT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciar Turma");

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Voltar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(0, 177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Voltar)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarTActionPerformed

        try {
            /*Pegando os valores dos Text Fields*/

            String ano = txtAno.getText().trim();
            String grupo = txtGrupo.getSelectedItem().toString();
            String curso = txtCurso.getText().trim();
            String periodo = txtPeriodo.getSelectedItem().toString();
            String nomeTurma = txtNomeTurma.getText().trim();

            /*Validação deve ser posta nessa área*/
            if (ano.isEmpty() || grupo.isEmpty() || curso.isEmpty() || periodo.isEmpty() || nomeTurma.isEmpty() || ano.equals("Ano que a turma cursa") || curso.equals("Curso da turma") || nomeTurma.equals("Apelido para a turma")) {
                JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos!");
                return;
            } else if (curso.length() > 30) {
                JOptionPane.showMessageDialog(rootPane, "O Campo curso deve ter entre 1-30 caracteres");
            } else if (nomeTurma.length() > 20) {
                JOptionPane.showMessageDialog(rootPane, "O canmpo Nome da Turma deve ter entre 1-20 caracteres");
            }
            int Ano;
            try {
                Ano = Integer.parseInt(ano);
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(rootPane, "O campo Ano deve ser um número válido!");
                return;
            }

            /*Criação de objetos*/
            Professor professor = Session.getInstancia().getProfessorLogado();
            ConProfessor conProfessor = new ConProfessor();

            Turma turma = new Turma();
            ConTurma conTurma = new ConTurma();

            /*Enviando para ConTurma*/
            turma.setANO_Turma(Ano);
            turma.setCOD_Professor(professor.getRM_Professor());
            turma.setGRUPO_Turma(grupo);
            turma.setCURSO_Turma(curso);
            turma.setPERIODO_Turma(periodo);
            turma.setNOME_Turma(nomeTurma);

            Boolean confirm = conTurma.cadTurma(turma);

            if (confirm) {
                JOptionPane.showMessageDialog(rootPane, "Registro Cadastrado com Sucesso!!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_cadastrarTActionPerformed

    private void excluirTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirTActionPerformed
        try {
            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir ?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {

                ConTurma conTurma = new ConTurma();

                /*Pega o id do aluno pesquisado, e usa para excluir*/
                int id;
                try {
                    id = Integer.parseInt(txtIdTurma.getText());
                    boolean confirm = conTurma.excluir(id);
                    if (confirm) {
                        /*Mensagem de sucesso*/
                        JOptionPane.showMessageDialog(rootPane, "Registro atualizado com sucesso!!!");
                    }
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Id invalido!");

                }

            }

        } catch (Exception ex) {
            /*Mensagem de erro*/
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro:" + ex);
        }
    }//GEN-LAST:event_excluirTActionPerformed

    private void editarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTActionPerformed
        try {

            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente editar ?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {

                /*Pegando os valores dos Text Fields*/
                String id = txtIdTurma.getText().trim();
                String ano = txtAno.getText().trim();
                String grupo = txtGrupo.getSelectedItem().toString();
                String curso = txtCurso.getText().trim();
                String periodo = txtPeriodo.getSelectedItem().toString();
                String nomeTurma = txtNomeTurma.getText().trim();

                /*Validação deve ser posta nessa área*/
                if (ano.isEmpty() || grupo.isEmpty() || curso.isEmpty() || periodo.isEmpty() || nomeTurma.isEmpty() || ano.equals("Ano que a turma cursa") || curso.equals("Curso da turma") || nomeTurma.equals("Apelido para a turma")) {
                    JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos!");
                    return;
                } else if (curso.length() > 30) {
                    JOptionPane.showMessageDialog(rootPane, "O Campo curso deve ter entre 1-30 caracteres");
                    return;
                } else if (nomeTurma.length() > 20) {
                    JOptionPane.showMessageDialog(rootPane, "O canmpo Nome da Turma deve ter entre 1-20 caracteres");
                    return;
                }
                int Ano, Id;
                try {
                    Id = Integer.parseInt(id);
                    Ano = Integer.parseInt(ano);
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(rootPane, "O campo Ano e Id devem ser um números válido!");
                    return;
                }

                /*Criação de objetos*/
                Professor professor = Session.getInstancia().getProfessorLogado();
                ConProfessor conProfessor = new ConProfessor();

                Turma turma = new Turma();
                ConTurma conTurma = new ConTurma();

                /*Enviando para ConTurma*/
                turma.setANO_Turma(Ano);
                turma.setCOD_Professor(professor.getRM_Professor());
                turma.setGRUPO_Turma(grupo);
                turma.setCURSO_Turma(curso);
                turma.setPERIODO_Turma(periodo);
                turma.setNOME_Turma(nomeTurma);
                turma.setID_Turma(Id);

                Boolean confirm = conTurma.editar(turma);

                if (confirm) {
                    JOptionPane.showMessageDialog(rootPane, "Registro Cadastrado com Sucesso!!");
                } else {
                    txtIdTurma.setText("");
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_editarTActionPerformed

    private void pesquisarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarTActionPerformed
        try {
            Turma turma = new Turma();
            ConTurma conTurma = new ConTurma();

            turma.setID_Turma(Integer.parseInt(txtIdTurma.getText()));
            turma = conTurma.pesquisarID(String.valueOf(turma.getID_Turma()));
            if (turma.getCURSO_Turma() != null) {
                txtAno.setText(String.valueOf(turma.getANO_Turma()));
                txtIdTurma.setText(String.valueOf(turma.getID_Turma()));
                if (turma.getGRUPO_Turma().equals("I")) {
                    txtGrupo.setSelectedItem("Inteiro");
                } else {
                    txtGrupo.setSelectedItem(turma.getGRUPO_Turma());
                }

                txtCurso.setText(turma.getCURSO_Turma());
                txtPeriodo.setSelectedItem(String.valueOf(turma.getPERIODO_Turma()));
                txtNomeTurma.setText(turma.getNOME_Turma());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Turma não encontrada");
                txtIdTurma.setText("");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }

    }//GEN-LAST:event_pesquisarTActionPerformed

    private void txtIdTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTurmaActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        try {
            MenuCad novaTela = new MenuCad();
            novaTela.setLocationRelativeTo(null);
            novaTela.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CadTurma.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JButton cadastrarT;
    private javax.swing.JButton editarT;
    private javax.swing.JButton excluirT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private BriamBank.Model.componentes.MenuLateral menuLateral1;
    private javax.swing.JButton pesquisarT;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JComboBox<String> txtGrupo;
    private javax.swing.JTextField txtIdTurma;
    private javax.swing.JTextField txtNomeTurma;
    private javax.swing.JComboBox<String> txtPeriodo;
    // End of variables declaration//GEN-END:variables
    /*txtEmailAluno.setText("E-Mail do Aluno");
        txtEmailAluno.setForeground(Color.GRAY);

        txtEmailAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtEmailAluno.getText().equals("E-Mail do Aluno")) {
                    txtEmailAluno.setText("");
                    txtEmailAluno.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtEmailAluno.getText().isEmpty()) {
                    txtEmailAluno.setText("E-Mail do Aluno");
                    txtEmailAluno.setForeground(Color.GRAY);
                }
            }
        });*/
    private void adicionarHintText() {

        //Hint do campo txtAno
        txtAno.setText("Ano que a turma cursa");
        txtAno.setForeground(Color.GRAY);

        txtAno.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtAno.getText().equals("Ano que a turma cursa")) {
                    txtAno.setText("");
                    txtAno.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtAno.getText().isEmpty()) {
                    txtAno.setText("Ano que a turma cursa");
                    txtAno.setForeground(Color.GRAY);
                }
            }
        });

        //Hint do campo txtCurso
        txtCurso.setText("Curso da turma");
        txtCurso.setForeground(Color.GRAY);

        txtCurso.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtCurso.getText().equals("Curso da turma")) {
                    txtCurso.setText("");
                    txtCurso.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtCurso.getText().isEmpty()) {
                    txtCurso.setText("Curso da turma");
                    txtCurso.setForeground(Color.GRAY);
                }
            }
        });

        //Hint do campo txtNomeTurma
        txtNomeTurma.setText("Apelido para a turma");
        txtNomeTurma.setForeground(Color.GRAY);

        txtNomeTurma.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtNomeTurma.getText().equals("Apelido para a turma")) {
                    txtNomeTurma.setText("");
                    txtNomeTurma.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtNomeTurma.getText().isEmpty()) {
                    txtNomeTurma.setText("Apelido para a turma");
                    txtNomeTurma.setForeground(Color.GRAY);
                }
            }
        });

        //Hint do campo txtIdTurma
        txtIdTurma.setText("ID da turma");
        txtIdTurma.setForeground(Color.GRAY);

        txtIdTurma.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtIdTurma.getText().equals("ID da turma")) {
                    txtIdTurma.setText("");
                    txtIdTurma.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtIdTurma.getText().isEmpty()) {
                    txtIdTurma.setText("ID da turma");
                    txtIdTurma.setForeground(Color.GRAY);
                }
            }
        });
    }
}
