/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConTurma;
import BriamBank.Model.Session;
import BriamBank.Model.Turma;
import BriamBank.Model.componentes.JCardGrupo;
import BriamBank.Model.componentes.JCardTurma;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.FlowLayout;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kauax
 */
public class GrupoMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(GrupoMenu.class.getName());

    private String NomeTurma; // Guarda o nome da turma selecionada

    // Construtor padrão (quando nenhuma turma é passada)
    public GrupoMenu() {

        // Se não houver professor logado, impede o acesso e fecha o programa
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane,
                    "Não é possivel acessar essa tela sem realizar o login, o programa será encerrado por segurança");
            System.exit(0);
        }

        // Define o ícone da janela
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        initComponents(); // Inicializa os componentes gráficos
    }

    // Construtor quando o nome de uma turma é passado
    public GrupoMenu(String NomeTurma) {

        // Mesma verificação para impedir acesso sem login
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane,
                    "Não é possível acessar essa tela sem realizar o login, o programa será encerrado por segurança");
            System.exit(0);
        }

        this.NomeTurma = NomeTurma; // Armazena a turma selecionada

        // Define o ícone da janela
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        initComponents(); // Inicializa os componentes

        // Busca todas as turmas cadastradas no banco
        ConTurma conTurma = new ConTurma();
        Vector<Turma> vetor = conTurma.RetornaTurmaCompleta(NomeTurma);

        // Define o layout para os cards serem empilhados verticalmente
        panelCards.setLayout(new BoxLayout(panelCards, BoxLayout.Y_AXIS));

        // Para cada turma encontrada, cria um card visual e adiciona ao painel
        for (int i = 0; i < vetor.size(); i++) {
            Turma t = vetor.get(i);

            JCardGrupo card = new JCardGrupo(
                    t.getNOME_Turma(),
                    t.getCURSO_Turma(),
                    t.getID_Turma(),
                    t.getGRUPO_Turma()
            );

            panelCards.add(card); // Adiciona o card na lista
        }

        // Atualiza o painel de cards após inserir tudo
        panelCards.revalidate();
        panelCards.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelt9 = new javax.swing.JLabel();
        menuLateral1 = new BriamBank.Model.componentes.MenuLateral();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelCards = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelt9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelt9.setText("Grupos");

        javax.swing.GroupLayout panelCardsLayout = new javax.swing.GroupLayout(panelCards);
        panelCards.setLayout(panelCardsLayout);
        panelCardsLayout.setHorizontalGroup(
            panelCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );
        panelCardsLayout.setVerticalGroup(
            panelCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelCards);

        jButton1.setBackground(new java.awt.Color(0, 122, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Excluir Turma");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelt9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelt9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             
            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir as turmas ?", "Confirmar", JOptionPane.YES_NO_OPTION);
            
            if (op == JOptionPane.YES_OPTION) {
                ConTurma conTurma = new ConTurma();

                // Mostra no console o nome da turma (provavelmente debug apenas)
                System.out.println("NomeTurma");

                // Busca todas as turmas com esse nome
                Vector<Turma> vetor = conTurma.RetornaTurmaCompleta(NomeTurma);

                // Exclui cada turma retornada
                for (int i = 0; i < vetor.size(); i++) {
                    Turma t = vetor.get(i);
                    conTurma.excluir(t.getID_Turma()); // Exclui pelo ID
                }

                // Após excluir, volta para a tela de MenuTurma
                MenuTurma novaTela = new MenuTurma();
                novaTela.setVisible(true);
                this.dispose(); // Fecha a tela atual
            }
            
            

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Método main para iniciar a aplicação com tema FlatLaf
    public static void main(String args[]) {

        try {
            // Deixa o visual igual ao do macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(GrupoMenu.class.getName())
                    .log(java.util.logging.Level.SEVERE,
                            "Falha ao inicializar FlatLaf", ex);
        }

        // Cria e mostra a tela
        java.awt.EventQueue.invokeLater(() -> new GrupoMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelt9;
    private javax.swing.JScrollPane jScrollPane1;
    private BriamBank.Model.componentes.MenuLateral menuLateral1;
    private javax.swing.JPanel panelCards;
    // End of variables declaration//GEN-END:variables
}
