/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConAluno;
import BriamBank.Controller.ConJustificativa;
import BriamBank.Controller.ConProfessor;
import BriamBank.Controller.ConTurma;
import BriamBank.Model.Justificativa;
import BriamBank.Model.Professor;
import BriamBank.Model.Session;
import BriamBank.Model.Turma;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel
 */
public class JustCad extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JustCad.class.getName());

    /**
     * Creates new form JustCad
     */
    public JustCad() {
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane, "Não é possivel acessar essa tela sem realizar o login, o programa será encerrado por segurança");
            System.exit(0);
        }
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        initComponents();
        adicionarHintText();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateral1 = new BriamBank.Model.componentes.MenuLateral();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        cadastrarT = new javax.swing.JButton();
        excluirT = new javax.swing.JButton();
        editarT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTurma = new javax.swing.JTextField();
        pesquisarT = new javax.swing.JButton();
        ComboStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Justificativa");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 97, 97)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Motivo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Status");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Descrição");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Quantidade");

        cadastrarT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarT.setText("Cadastrar");
        cadastrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarTActionPerformed(evt);
            }
        });

        excluirT.setBackground(new java.awt.Color(0, 122, 255));
        excluirT.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        excluirT.setForeground(new java.awt.Color(255, 255, 255));
        excluirT.setText("Excluir");
        excluirT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirTActionPerformed(evt);
            }
        });

        editarT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editarT.setText("Editar");
        editarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Id da Justificativa");

        pesquisarT.setText("Pesquisar");
        pesquisarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarTActionPerformed(evt);
            }
        });

        ComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        ComboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(600, 600, 600))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(634, 634, 634))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluirT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editarT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(216, 216, 216))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(202, 202, 202))
                            .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(286, 286, 286))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(pesquisarT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComboStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMotivo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesquisarT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(excluirT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastrarT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarTActionPerformed
        try {
            /*Pegando os valores dos Text Fields*/
            String Motivo = txtMotivo.getText().trim();
            String Status = (String) ComboStatus.getSelectedItem();
            String Desc = txtDesc.getText().trim();
            String Qtd = txtQtd.getText();


            /*Validação deve ser posta nessa área*/
            if (Motivo.isEmpty() || Desc.isEmpty() || Qtd.isEmpty() || Motivo.equals("Insira o motivo") || Desc.equals("Insira a descrição") || Qtd.equals("Insira a quantidade de pontos")) {
                JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos!");
                return;
            } else if (Motivo.length() > 20) {
                JOptionPane.showMessageDialog(rootPane, "O motivo deve ter no máximo 20 caracteres");
                return;
            } else if (Desc.length() > 30) {
                JOptionPane.showMessageDialog(rootPane, "A descrição deve ter no máximo 30 caracteres");
                return;
            }
            double qtd;

            try {
                qtd = Double.parseDouble(Qtd);
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(rootPane, "O campo Quantidade deve ser um numero valido!");
                return;
            }
            if (qtd == 0) {
                JOptionPane.showMessageDialog(rootPane, "A quantidade de pontos não pode ser 0");
                return;
            }

            ConJustificativa conJust = new ConJustificativa();
            Boolean confirm = conJust.CadastrarJust(Desc, Motivo, qtd, Status);
            if (confirm) {
                JOptionPane.showMessageDialog(rootPane, "Registro Cadastrado com Sucesso!!");
                listar();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_cadastrarTActionPerformed

    private void excluirTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirTActionPerformed
        try {
            int id = Integer.parseInt(txtTurma.getText());

            if (id == 1 || id == 7) {
                JOptionPane.showMessageDialog(rootPane, "Não é possivel excluir justificativa 'Novo Aluno'/'Outro'");
            } else {

                int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir ?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (op == JOptionPane.YES_OPTION) {
                    ConJustificativa conJust = new ConJustificativa();

                    /*Pega o id do aluno pesquisado, e usa para excluir*/
                    conJust.ExcluirJust(id);

                    /*Mensagem de sucesso*/
                    JOptionPane.showMessageDialog(rootPane, "Registro atualizado com sucesso!!!");
                    listar();
                }
            }
        } catch (Exception ex) {
            /*Mensagem de erro*/
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro:" + ex);
        }
    }//GEN-LAST:event_excluirTActionPerformed

    private void editarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTActionPerformed
        try {

            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente editar?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                /*Pegando os valores dos Text Fields*/
                String Id = txtTurma.getText().trim();
                String Motivo = txtMotivo.getText().trim();
                String Status = ComboStatus.getSelectedItem().toString();
                String Desc = txtDesc.getText().trim();
                String Qtd = txtQtd.getText();


                /*Validação deve ser posta nessa área*/
                if (Motivo.isEmpty() || Desc.isEmpty() || Qtd.isEmpty() || Motivo.equals("Insira o motivo") || Desc.equals("Insira a descrição") || Qtd.equals("Insira a quantidade de pontos")) {
                    JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos!");
                    return;
                } else if (Motivo.length() > 20) {
                    JOptionPane.showMessageDialog(rootPane, "O motivo deve ter no máximo 20 caracteres");
                    return;
                } else if (Desc.length() > 30) {
                    JOptionPane.showMessageDialog(rootPane, "A descrição deve ter no máximo 30 caracteres");
                    return;
                }
                double qtd;
                int id;
                try {
                    id = Integer.parseInt(Id);
                    qtd = Double.parseDouble(Qtd);
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(rootPane, "Os campos IdTurma e Quantidade deve ser numeros valido!");
                    return;
                }

                if (qtd == 0) {
                    JOptionPane.showMessageDialog(rootPane, "A quantidade de pontos não pode ser 0");
                    return;
                }

                // String Desc, String Motivo, Double qtd, String Status, int id
                ConJustificativa conJust = new ConJustificativa();
                Boolean confirm = conJust.EditarJust(Desc, Motivo, qtd, Status, id);
                if (confirm) {
                    JOptionPane.showMessageDialog(rootPane, "Edição feita com Sucesso!!");
                    listar();
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_editarTActionPerformed

    private void pesquisarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarTActionPerformed
            try {
        // Captura o texto digitado no campo de ID e remove espaços extras
        String Id = txtTurma.getText().trim();

        int id;
        try {
            // Tenta converter o valor digitado para número inteiro
            id = Integer.parseInt(Id);
        } catch (NumberFormatException nfe) {
            // Caso o valor não seja um número, mostra erro e interrompe o processo
            JOptionPane.showMessageDialog(rootPane, "O campo IdTurma deve ser um numero valido!");
            return;
        }

        // Cria o controlador responsável por acessar as justificativas no banco
        ConJustificativa conJust = new ConJustificativa();

        // Busca no banco a justificativa referente ao ID informado
        Justificativa just = conJust.retornaJust(id);

        // Verifica se a justificativa retornou um status (se existir no banco)
        if (just.getSTATUS_Just() != null) {

            // Converte o valor booleano em texto para exibir no ComboBox
            String status;
            if (just.getSTATUS_Just() == false) {
                status = "Inativo";
            } else {
                status = "Ativo";
            }

            // Preenche os campos da interface com os dados retornados do banco
            txtMotivo.setText(just.getMOTIVO_Justificativa());
            ComboStatus.setSelectedItem(status);
            txtDesc.setText(just.getDESC_Justificativa());
            txtQtd.setText(String.valueOf(just.getQTD_Justificativa()));

        } else {
            // Caso a justificativa não exista no banco
            JOptionPane.showMessageDialog(rootPane, "Justificativa não encontrada");
        }

    } catch (Exception ex) {
        // Trata qualquer erro inesperado durante o processo de consulta
        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        txtTurma.setText(""); // Limpa o campo de entrada
    }

    }//GEN-LAST:event_pesquisarTActionPerformed

    private void ComboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboStatusActionPerformed

    }//GEN-LAST:event_ComboStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(JustCad.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JustCad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboStatus;
    private javax.swing.JButton cadastrarT;
    private javax.swing.JButton editarT;
    private javax.swing.JButton excluirT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private BriamBank.Model.componentes.MenuLateral menuLateral1;
    private javax.swing.JButton pesquisarT;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtTurma;
    // End of variables declaration//GEN-END:variables
    public void listar() {
    Vector cabecalho = new Vector();
        try {
            // Define os nomes das colunas da tabela
            cabecalho.addElement("IdJust");
            cabecalho.addElement("Data");
            cabecalho.addElement("Quantidade");
            cabecalho.addElement("Descrição");
            cabecalho.addElement("Motivo");
            cabecalho.addElement("Status");

            // Controlador responsável por buscar as justificativas no banco
            ConJustificativa conJust = new ConJustificativa();

            // Verifica se houve falha ao tentar buscar os dados
            if (conJust.RetornaJusts() == null) {
                JOptionPane.showMessageDialog(rootPane, "Ocorreu uma falha durante a exibição dos dados, tente novamente mais tarde");
            }

            // Atualiza a tabela com os dados retornados do banco
            jTable1.setModel(new DefaultTableModel(conJust.RetornaJusts(), cabecalho));

        } catch (Exception ex) {
            // Caso ocorra um erro inesperado durante a listagem
            JOptionPane.showMessageDialog(rootPane, "Ocorreu uma falha durante a exibição dos dados, tente novamente mais tarde");
        }
}

    private void adicionarHintText() {

        // Configura texto de dica para txtTurma
        txtTurma.setText("Insira o Id da Justificativa");
        txtTurma.setForeground(Color.GRAY);

        txtTurma.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                // Remove a dica quando o usuário clica no campo
                if (txtTurma.getText().equals("Insira o Id da Justificativa")) {
                    txtTurma.setText("");
                    txtTurma.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                // Restaura a dica caso o campo fique vazio
                if (txtTurma.getText().isEmpty()) {
                    txtTurma.setText("Insira o Id da Justificativa");
                    txtTurma.setForeground(Color.GRAY);
                }
            }
        });

        // Configura texto de dica para txtMotivo
        txtMotivo.setText("Insira o motivo");
        txtMotivo.setForeground(Color.GRAY);

        txtMotivo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtMotivo.getText().equals("Insira o motivo")) {
                    txtMotivo.setText("");
                    txtMotivo.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtMotivo.getText().isEmpty()) {
                    txtMotivo.setText("Insira o motivo");
                    txtMotivo.setForeground(Color.GRAY);
                }
            }
        });

        // Configura texto de dica para txtDesc
        txtDesc.setText("Insira a descrição");
        txtDesc.setForeground(Color.GRAY);

        txtDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtDesc.getText().equals("Insira a descrição")) {
                    txtDesc.setText("");
                    txtDesc.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtDesc.getText().isEmpty()) {
                    txtDesc.setText("Insira a descrição");
                    txtDesc.setForeground(Color.GRAY);
                }
            }
        });

        // Configura texto de dica para txtQtd
        txtQtd.setText("Insira a quantidade de pontos");
        txtQtd.setForeground(Color.GRAY);

        txtQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtQtd.getText().equals("Insira a quantidade de pontos")) {
                    txtQtd.setText("");
                    txtQtd.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtQtd.getText().isEmpty()) {
                    txtQtd.setText("Insira a quantidade de pontos");
                    txtQtd.setForeground(Color.GRAY);
                }
            }
        });
      }
}
