/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConProfessor;
import BriamBank.Model.Professor;
import BriamBank.Model.Session;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.*;

/**
 *
 * @author Miguel
 */
public class Login extends javax.swing.JFrame {

    //declara um logger estático e imutável associado à classe Login
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Loguin
     */
    public Login() {
        /*Adiciona o icone na janela */
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        /*Carrega os componentes da tela*/
        initComponents();

        /*Adiciona os hints nos campos de texto*/
        adicionarHintText();

        /*Quando a tela fechar vai dar foco na jLabel1*/
        java.awt.EventQueue.invokeLater(() -> {
            jLabel1.requestFocusInWindow();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRM = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSenha1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("BrianBank");

        txtRM.setToolTipText("");
        txtRM.setPreferredSize(new java.awt.Dimension(128, 44));

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 122, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logar");
        jButton2.setPreferredSize(new java.awt.Dimension(128, 44));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 122, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cadastrar");
        jButton3.setPreferredSize(new java.awt.Dimension(128, 44));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnSenha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/view.png"))); // NOI18N
        btnSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenha1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(125, 125, 125)
                .addComponent(txtRM, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSenha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /*Btn de logar*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            /*Pega o valor posto em ambos os campos   */
            String rmText = txtRM.getText().trim();
            String senha = new String(txtSenha.getPassword()).trim();

            if (rmText.equals("Admin") && senha.equals("Admin")) {
                /*Chama atela MenuTurma*/
                Admin novaTela = new Admin();
                novaTela.setVisible(true);
                /*Apaga tela atual*/
                this.dispose();
                return;

            }

            /*Garante que nenhum deles esteja vazio*/
            if (rmText.isEmpty() || rmText.equals("Digite seu RM")
                    || senha.isEmpty() || senha.equals("Digite sua senha")) {

                /*Mensagem pedindo para preencher os campos*/
                JOptionPane.showMessageDialog(rootPane, "Todos os campos devem estar preenchidos");
                return;
                /*Caso o RM não cotenha apenas números*/
            } else if (!rmText.matches("\\d+")) {
                JOptionPane.showMessageDialog(rootPane, "O RM deve conter apenas números!");
                return;
                /*Se o RM não tiver exatamente 5 digitos*/
            } else if (rmText.length() != 5) {
                JOptionPane.showMessageDialog(rootPane, "O RM deve ter exatamente 5 dígitos.");
                return;
                /*Se a senha não estiver no intervalo de 8 e 32 caracteres*/
            } else if (senha.length() < 8 || senha.length() > 32) {
                JOptionPane.showMessageDialog(rootPane, "A senha deve ter entre 8 e 32 caracteres");
                return;
            }

            /*Atribui o valor do RM digitado á variavel rm*/
            int rm = Integer.parseInt(rmText);

            /*Instancia respectivamente os objetos: Conprofessor e Professor*/
            ConProfessor con = new ConProfessor();
            Professor prof = new Professor();

            /*Seta o RM e senha do professor como o que teve as informações inseridas*/
            prof.setRM_Professor(rm);
            prof.setSENHA_Professor(senha);

            /*Vê se as informações inseridas conferem, se não retorna null*/
            prof = con.logar(prof);

            /*Se prof for NÃO null, então ele existe e suas informções batem*/
            if (prof != null) {
                /*Informa que deu certo e diz que usuário foi logado*/
                JOptionPane.showMessageDialog(rootPane,
                        "Login realizado com sucesso! Bem-vindo(a): " + prof.getNome_Professor());
                /*Chama atela MenuTurma*/
                MenuTurma novaTela = new MenuTurma();
                novaTela.setVisible(true);
                /*Apaga tela atual*/
                this.dispose();
            } else {
                /*Caso as informaçõe snão baterem*/
                JOptionPane.showMessageDialog(rootPane, "RM ou Senha incorretos");
            }

        } catch (Exception ex) {
            /*Caso ocorra algum outro erro*/
            JOptionPane.showMessageDialog(rootPane, "Um erro inesperado ocorreu: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /*Botão de cadastrar*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            /*Chama a tela CadastroProfessor*/
            CadastroProfessor novaTela = new CadastroProfessor();
            novaTela.setVisible(true);
            /*Apaga a tela atual*/
            this.dispose();
        } catch (Exception ex) {
            /*Mensagem de erro*/
            JOptionPane.showMessageDialog(rootPane, "Um erro inesperado ocorreu: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed
    /*Btn de revelar/esconder senha*/
    private void btnSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenha1ActionPerformed
        try {
            /*EcgoChar é o caractere usado para mascarar a senha, getEchoChar retorna o caracter usado, se for o mesmo, executa o if*/
            if (txtSenha.getEchoChar() == '•') {
                txtSenha.setEchoChar((char) 0); //Desativa a mascara
                /*muda a imagem do botão de revelar/esconder senha*/
                btnSenha1.setIcon(new ImageIcon(getClass().getResource("/assets/icons/hide.png")));
            } else {
                txtSenha.setEchoChar('•'); // volta a mascarar
                /*muda aimagem do botão de revelar/esconder senha*/
                btnSenha1.setIcon(new ImageIcon(getClass().getResource("/assets/icons/view.png")));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_btnSenha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSenha1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtRM;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
private void adicionarHintText() {
        // === HINT do campo RM ===
        txtRM.setText("Digite seu RM");
        txtRM.setForeground(Color.GRAY);

        txtRM.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtRM.getText().equals("Digite seu RM")) {
                    txtRM.setText("");
                    txtRM.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtRM.getText().isEmpty()) {
                    txtRM.setText("Digite seu RM");
                    txtRM.setForeground(Color.GRAY);
                }
            }
        });

        // === HINT do campo SENHA ===
        txtSenha.setText("Digite sua senha");
        txtSenha.setForeground(Color.GRAY);
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtSenha.getText().equals("Digite sua senha")) {
                    txtSenha.setText("");
                    txtSenha.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtSenha.getText().isEmpty()) {
                    txtSenha.setText("Digite sua senha");
                    txtSenha.setForeground(Color.GRAY);
                }
            }
        });
    }

}
