/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConTurma;
import BriamBank.Model.Session;
import BriamBank.Model.Turma;
import BriamBank.Model.componentes.JCardTurma;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.FlowLayout;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author LABINFO
 */
public class MenuTurma extends javax.swing.JFrame {

    /**
     * Creates new form CadTurma
     */
    public MenuTurma() {
        /*Garante que o user esteja logado*/
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane, "Não é possivel acessar essa tela sem realizar o login, o programa será encerrado por segurança");
            System.exit(0);
        }
        /*Define o icone da janela*/
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        /*Carrega os componentes da tela*/
        initComponents();
        
        
        try {
            /*Instancia e cria o objeto Conturma*/
            ConTurma conTurma = new ConTurma();
            
            /*cria um vetor para listar as turmas*/
            Vector<Turma> vetor = conTurma.retornar_turmas();
            //Define como os componentes desse panel devem ser organizados
            panelCards.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 20));

             /*Pega todos os nomes guarda na variavel nomesUnicos, mas sem incluir repetições */
            Set<String> nomesUnicos = new HashSet<>();

              /*Repitição para adicionar todos os cards necessários */
            for (int i = 0; i < vetor.size(); i++) {
                
                /*Sleciona a turma que vai ter as informações coletadas e guarda na variavel t*/
                Turma t = vetor.get(i);

                 /*Verifica se o nome da turma ainda não está no conjunto nomesUnicos. Se for um nome novo, adiciona ao conjunto.*/
                if (!nomesUnicos.contains(t.getNOME_Turma())) {
                     /*Cria o card de turma de uma turma que ainda não tem seu card */
                    nomesUnicos.add(t.getNOME_Turma());
                    JCardTurma card = new JCardTurma(t.getNOME_Turma(), t.getCURSO_Turma(), t.getID_Turma());
                    
                    /*Adiciona o card criado na lista*/
                    panelCards.add(card);
                }
            }

            /*Caso alguma turma tenha sdio excluida, ela é removida e a interface é atualizada*/
            panelCards.revalidate();
            panelCards.repaint();
        } catch (Exception ex) {
            /*Mensagem de erro*/
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        menuLateral1 = new BriamBank.Model.componentes.MenuLateral();
        panelCards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Turmas");

        javax.swing.GroupLayout panelCardsLayout = new javax.swing.GroupLayout(panelCards);
        panelCards.setLayout(panelCardsLayout);
        panelCardsLayout.setHorizontalGroup(
            panelCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCardsLayout.setVerticalGroup(
            panelCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9)
                        .addGap(0, 945, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(panelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MenuTurma.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private BriamBank.Model.componentes.MenuLateral menuLateral1;
    private javax.swing.JPanel panelCards;
    // End of variables declaration//GEN-END:variables
}
