/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BriamBank.View;

import BriamBank.BrianBank;
import BriamBank.Controller.ConAluno;
import BriamBank.Controller.ConJustificativa;
import BriamBank.Controller.ConPontos;
import BriamBank.Model.Aluno;
import BriamBank.Model.Justificativa;
import BriamBank.Model.Pontos;
import BriamBank.Model.Session;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kauax
 */
public class MudarPontos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MudarPontos.class.getName());

    /**
     * Creates new form Pontos
     */
    public MudarPontos() {
        if (Session.getInstancia().getProfessorLogado() == null) {
            JOptionPane.showMessageDialog(rootPane, "Não é possivel acessar essa tela sem realizar o login, o programa será encerrado por segurança");
            System.exit(0);
        }
        ImageIcon icon = new ImageIcon(BrianBank.class.getResource("/assets/icons/bblogo.png"));
        setIconImage(icon.getImage());

        initComponents();
        adicionarHintText();
        PreencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateral1 = new BriamBank.Model.componentes.MenuLateral();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQtdPontos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPontos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdAluno = new javax.swing.JTextField();
        pesquisarA = new javax.swing.JButton();
        comboJustificativas = new javax.swing.JComboBox<>();
        cadastrarA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 97, 97)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome Aluno");

        txtNomeAluno.setEditable(false);
        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Quantidade Total de Pontos");

        txtQtdPontos.setEditable(false);
        txtQtdPontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdPontosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Justificativas");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Pontos Retirados/Adicionados");

        txtPontos.setEditable(false);
        txtPontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Id do Aluno");

        pesquisarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pesquisarA.setText("Pesquisar");
        pesquisarA.setActionCommand("");
        pesquisarA.setBorder(null);
        pesquisarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAActionPerformed(evt);
            }
        });

        comboJustificativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJustificativasActionPerformed(evt);
            }
        });

        cadastrarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarA.setText("Cadastrar");
        cadastrarA.setBorder(null);
        cadastrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboJustificativas, 0, 226, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(txtQtdPontos)
                        .addComponent(jLabel4)
                        .addComponent(txtPontos))
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisarA, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(302, 302, 302))
                    .addComponent(cadastrarA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQtdPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboJustificativas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(cadastrarA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pontos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void txtQtdPontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdPontosActionPerformed

    }//GEN-LAST:event_txtQtdPontosActionPerformed

    private void txtPontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosActionPerformed
        try {

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_txtPontosActionPerformed

    private void pesquisarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAActionPerformed
        try {
            Pontos pontos = new Pontos();
            ConPontos conPontos = new ConPontos();

            pontos = conPontos.PesquisarPontos(txtIdAluno.getText());

            if (pontos != null) {
                if (pontos.getQTD_Pontos() != null) {
                    txtIdAluno.setText(String.valueOf(pontos.getCOD_Aluno()));
                    txtNomeAluno.setText(pontos.getNOME_Aluno());
                    txtQtdPontos.setText(String.valueOf(pontos.getQTD_Pontos()));
                } else if (pontos.getQTD_Pontos() == null) {
                    JOptionPane.showMessageDialog(rootPane, "Não é possivel consultar alunos de outros professores ou alunos inexistentes ");
                    txtIdAluno.setText("");
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_pesquisarAActionPerformed

    private void comboJustificativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJustificativasActionPerformed
        try {
            if (String.valueOf(comboJustificativas.getSelectedItem()).equals("Outro")) {
                txtPontos.setEditable(true);
            } else {
                txtPontos.setEditable(false);
                ConJustificativa conJust = new ConJustificativa();

                Justificativa just = conJust.retornaJust(String.valueOf(comboJustificativas.getSelectedItem()));

                txtPontos.setText(String.valueOf(just.getQTD_Justificativa()));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex);
        }
    }//GEN-LAST:event_comboJustificativasActionPerformed

    private void cadastrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAActionPerformed
        try {
            String CodAluno = txtIdAluno.getText().trim();
            String NomeAluno = txtNomeAluno.getText().trim();
            String TotPontos = txtQtdPontos.getText().trim();
            String Just = (String) comboJustificativas.getSelectedItem();
            String EdtPontos = txtPontos.getText().trim();
            
            if (String.valueOf(comboJustificativas.getSelectedItem()).equals("Novo aluno")){
                
            JOptionPane.showMessageDialog(rootPane, "Não é possivel utilizar a justivificativa novo aluno, pois o aluno já está cadastrado");
            
            }
            else{
            
            if (EdtPontos.equals("0")){
              JOptionPane.showMessageDialog(rootPane, "Não é possivel cadastrar 0 pontos!");
              return;
            }
            
            if (CodAluno.isEmpty() || NomeAluno.isEmpty() || TotPontos.isEmpty() || Just.isEmpty() || EdtPontos.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos!");
                return;
            }
             
            int idAluno;
            try {

                idAluno = Integer.parseInt(CodAluno);

            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(rootPane, "O campo de Id do aluno deve ser um número válido!");
                return;
            }
            Double PontosAlt;
            try {
                PontosAlt = Double.parseDouble(EdtPontos);

            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(rootPane, "O campo de Pontos deve ser um número válido!");
                return;
            }
            /*Converter Int em Double é sempre uma vlidação segura, ou seja, não há
            necessidade de verificação (se for pra dar erro vai dar antes)*/
            double Points = PontosAlt;

            ConJustificativa conJust = new ConJustificativa();
            Justificativa just = new Justificativa();

            Pontos pontos = new Pontos();
            ConPontos conPontos = new ConPontos();

            just = conJust.retornaJust(Just);

            pontos.setCOD_Justificativa(just.getID_Justificativa());
            pontos.setQTD_Pontos(Points);
            pontos.setCOD_Aluno(idAluno);

            conPontos.cadastroPontos(pontos.getCOD_Justificativa(), pontos.getQTD_Pontos(), pontos.getCOD_Aluno());

            JOptionPane.showMessageDialog(rootPane, "Registro Cadastrado com Sucesso!!");
            
          }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_cadastrarAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Configura FlatLaf estilo macOS claro
            FlatMacLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MudarPontos.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Falha ao inicializar FlatLaf", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MudarPontos().setVisible(true));
    }

    public void PreencherCombo() {
        try {
            ConJustificativa conJust = new ConJustificativa();
            Vector lista = conJust.RetornaJusts();

            comboJustificativas.removeAllItems();

            for (int i = 0; i < lista.size(); i++) {
                Vector linha = (Vector) lista.get(i);

                String status = String.valueOf(linha.get(5));

                if (!"false".equalsIgnoreCase(status)) {
                    if (!linha.get(4).equals("Novo aluno")) {
                        String motivo = String.valueOf(linha.get(4));
                        comboJustificativas.addItem(motivo);
                    }
                    
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combo: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarA;
    private javax.swing.JComboBox<String> comboJustificativas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private BriamBank.Model.componentes.MenuLateral menuLateral1;
    private javax.swing.JButton pesquisarA;
    private javax.swing.JTextField txtIdAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtPontos;
    private javax.swing.JTextField txtQtdPontos;
    // End of variables declaration//GEN-END:variables
    private void adicionarHintText() {

        txtIdAluno.setText("Insira o Id do Aluno");
        txtIdAluno.setForeground(Color.GRAY);

        txtIdAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtIdAluno.getText().equals("Insira o Id do Aluno")) {
                    txtIdAluno.setText("");
                    txtIdAluno.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtIdAluno.getText().isEmpty()) {
                    txtIdAluno.setText("Insira o Id do Aluno");
                    txtIdAluno.setForeground(Color.GRAY);
                }
            }
        });

    }
}
